export class APICode {
	static SUCCESS = 'SUCCESS';
	static UNKNOWN_ERROR = 'UNKNOWN_ERROR';
	static UNAUTHORIZED = 'UNAUTHORIZED';
	static PERMISSION_DENIED = 'PERMISSION_DENIED';
	static IN_VALID_PARAMS = 'IN_VALID_PARAMS';
}
